declare module '@editorjs/list'
declare module '@editorjs/simple-image'
declare module '@editorjs/checklist'
declare module '@editorjs/embed'
declare module '@editorjs/link'
declare module '@editorjs/table'
declare module '@editorjs/header'
declare module '@editorjs/marker'
declare module '@editorjs/underline '
declare module '@editorjs/code '
declare module 'editorjs-drag-drop'
declare module 'editorjs-undo '
declare module '@editorjs/inline-code'
declare module '@editorjs/underline'
declare module '@editorjs/code'
declare module 'editorjs-undo'
declare module '@editorjs/image'
declare module '@editorjs/paragraph'
// // eslint-disable-next-line no-undef
// export type Never = { [P in keyof T]?: never }
